#!/usr/bin/env python3
"""
Validates card_data.py and generates CardBank.swift from it.
Run: python3 build_cardbank.py
"""
import sys
import os
from card_data import CARDS

VALID_TOPICS = {
    "mathematics", "probabilityStatistics", "ethicsEconomics", "electricityMagnetism",
    "statics", "dynamics", "mechanicsOfMaterials", "materialProperties",
    "fluidMechanics", "thermodynamics", "heatTransfer", "measurementsControls",
    "mechanicalDesign", "generalME",
}
VALID_KINDS = {"quiz", "flashcard", "formula", "handbookLookup"}


def validate():
    errors = []
    seen_ids = set()
    topic_counts = {t: 0 for t in VALID_TOPICS}

    for i, c in enumerate(CARDS):
        loc = f"card #{i} (id={c.get('id')!r})"

        if not c["id"]:
            errors.append(f"{loc}: empty id")
        if c["id"] in seen_ids:
            errors.append(f"{loc}: duplicate id")
        seen_ids.add(c["id"])

        if c["topic"] not in VALID_TOPICS:
            errors.append(f"{loc}: unknown topic {c['topic']!r}")
        else:
            topic_counts[c["topic"]] += 1

        if c["kind"] not in VALID_KINDS:
            errors.append(f"{loc}: unknown kind {c['kind']!r}")

        if not c["prompt"] or not c["prompt"].strip():
            errors.append(f"{loc}: empty prompt")
        if not c["explanation"] or not c["explanation"].strip():
            errors.append(f"{loc}: empty explanation")
        if not c["handbookRef"] or not c["handbookRef"].strip():
            errors.append(f"{loc}: empty handbookRef")

        if c["kind"] == "quiz":
            if not c["choices"] or len(c["choices"]) < 2:
                errors.append(f"{loc}: quiz needs >=2 choices")
            elif c["correctIndex"] is None:
                errors.append(f"{loc}: quiz missing correctIndex")
            elif not (0 <= c["correctIndex"] < len(c["choices"])):
                errors.append(f"{loc}: correctIndex {c['correctIndex']} out of range for {len(c['choices'])} choices")
            if c["answer"] is not None:
                errors.append(f"{loc}: quiz card should not set 'answer' (use choices/correctIndex)")
        else:
            if c["choices"] is not None or c["correctIndex"] is not None:
                errors.append(f"{loc}: non-quiz card should not set choices/correctIndex")
            if c["kind"] in ("flashcard", "formula") and (not c["answer"] or not c["answer"].strip()):
                errors.append(f"{loc}: {c['kind']} card missing answer")
            if c["kind"] == "handbookLookup" and c["answer"] is not None:
                errors.append(f"{loc}: handbookLookup card should not set 'answer' (use handbookRef/explanation)")

    for topic, count in topic_counts.items():
        if count == 0:
            errors.append(f"topic {topic!r} has zero cards")
        elif count < 5:
            errors.append(f"WARNING: topic {topic!r} has only {count} cards")

    return errors, topic_counts


def swift_string_literal(s: str) -> str:
    """Escape a Python string for embedding in a Swift string literal."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def swift_optional_string_array(arr):
    if arr is None:
        return "nil"
    items = ", ".join(swift_string_literal(x) for x in arr)
    return f"[{items}]"


def swift_optional_int(v):
    return "nil" if v is None else str(v)


def swift_optional_string(v):
    return "nil" if v is None else swift_string_literal(v)


def generate_swift(cards) -> str:
    lines = []
    lines.append("//")
    lines.append("//  CardBank.swift")
    lines.append("//  FEStudyFeed")
    lines.append("//")
    lines.append("//  AUTO-GENERATED by build_cardbank.py from card_data.py.")
    lines.append("//  Do not hand-edit this file directly -- edit the source data instead")
    lines.append("//  and regenerate, so the two never drift apart.")
    lines.append("//")
    lines.append("//  Content is original, written from general engineering knowledge for")
    lines.append("//  FE Mechanical exam prep. It is not copied from the NCEES FE Reference")
    lines.append("//  Handbook; handbookRef fields point to where a concept lives in that")
    lines.append("//  handbook so the reader can go look it up themselves.")
    lines.append("//")
    lines.append("")
    lines.append("import Foundation")
    lines.append("")
    lines.append("enum CardBank {")
    lines.append(f"    static let all: [StudyCard] = [")
    for c in cards:
        lines.append("        StudyCard(")
        lines.append(f"            id: {swift_string_literal(c['id'])},")
        lines.append(f"            topic: .{c['topic']},")
        lines.append(f"            kind: .{c['kind']},")
        lines.append(f"            prompt: {swift_string_literal(c['prompt'])},")
        lines.append(f"            choices: {swift_optional_string_array(c['choices'])},")
        lines.append(f"            correctIndex: {swift_optional_int(c['correctIndex'])},")
        lines.append(f"            answer: {swift_optional_string(c['answer'])},")
        lines.append(f"            explanation: {swift_string_literal(c['explanation'])},")
        lines.append(f"            handbookRef: {swift_string_literal(c['handbookRef'])}")
        lines.append("        ),")
    lines.append("    ]")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    errors, counts = validate()
    hard_errors = [e for e in errors if not e.startswith("WARNING")]
    warnings = [e for e in errors if e.startswith("WARNING")]

    print(f"Total cards: {len(CARDS)}")
    for t in sorted(counts):
        print(f"  {t:24s} {counts[t]:3d}")

    for w in warnings:
        print(w)

    if hard_errors:
        print(f"\n{len(hard_errors)} ERROR(S):")
        for e in hard_errors:
            print(" -", e)
        sys.exit(1)

    swift_src = generate_swift(CARDS)
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "FEStudyFeed", "CardBank.swift")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(swift_src)
    print(f"\nOK -- wrote {out_path} ({len(CARDS)} cards, no errors)")
